spring.application.name=secy
logging.level.net.jdesive=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5433/secy
spring.datasource.username=secy
spring.datasource.password=secy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

nvd.apikey=${NVD_API_KEY}